name: Build bg

on:
  push:
    branches: [main]
    paths:
      - 'apps/bg/**'
      - 'packages/**'
      - '.github/workflows/bg.yml'
  pull_request:
    branches: [main]
    paths:
      - 'apps/bg/**'
      - 'packages/db/**'
      - 'packages/channel-sync/**'
      - '.github/workflows/bg.yml'

permissions:
  contents: read
  id-token: write

jobs:
  build:
    runs-on: depot-ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - name: Setup JFrog Fly
        uses: jfrog/fly-action@v1
        with:
          url: https://t3content.jfrog.io

      - name: Set up Depot CLI
        uses: depot/setup-action@v1

      - name: Build Docker image
        run: |
          depot build \
            -f docker/Dockerfile.bg \
            -t t3content.jfrog.io/docker/r8y-bg:${{ github.sha }} \
            -t t3content.jfrog.io/docker/r8y-bg:latest \
            --push
            .
        env: 
          DEPOT_TOKEN: ${{ secrets.DEPOT_SECRET }}

